spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dw_study?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: qwer
      
mybatis:
   mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
   type-aliases-package: com.dw.emp.vo